# Generated by Django 4.2.22 on 2025-10-18 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0004_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTaskSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("param_p", models.IntegerField()),
                ("task_id", models.IntegerField()),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_sessions",
                        to="Dashboard.userprofile",
                    ),
                ),
            ],
        ),
    ]
